# Generated by Django 3.1.3 on 2020-11-06 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='players',
            options={'managed': False},
        ),
    ]
