# Generated by Django 3.1.3 on 2020-11-06 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20201106_0014'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='players',
            table='Player',
        ),
    ]
