# Generated by Django 3.1.3 on 2020-11-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_searchplayers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('team_name', models.CharField(max_length=30)),
                ('year_founded', models.IntegerField()),
            ],
            options={
                'db_table': 'Teams',
                'managed': False,
            },
        ),
    ]
