# Generated by Django 3.1.3 on 2020-11-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlayers',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('season_id', models.CharField(max_length=10)),
                ('team_id', models.IntegerField()),
                ('player_name', models.CharField(max_length=30)),
                ('points', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
