# Generated by Django 3.1.3 on 2020-11-30 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_userplayers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userplayers',
            table='User',
        ),
    ]
