# Generated by Django 3.1.3 on 2020-11-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20201130_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('season_id', models.CharField(blank=True, max_length=45, null=True)),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('player_name', models.CharField(blank=True, max_length=45, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'User2',
                'managed': False,
            },
        ),
    ]
